### ISSUE TITLE
openconf.cfg is not update when running make menuconfig

### ISSUE THREAD

**Issue by jean-marc-LACROIX** [sbxg/sbxg#3] opened 2016-03-05 20:50 UTC
When running `make menuconfig` on top of DIR, if openconf.cfg.in is modified, changes are not visible in menuconfig.
It seems this file (openconf.cfg.in) is parsed by make somewhere ....

**Comment by jeanguyomarch** [comment] 2016-03-06 11:20
I was unable to reproduce the issue.
This is how is proceeded:
1. Run `make menuconfig`;
2. Observe the help of `Distribution/Hostname`;
3. Edit `conf/openconf.cgf.in` by writing the help section;
4. Re-run `make menuconfig`;
5. `Distribution/Hostname`'s help changed as expected.

Can you try again the steps above and check if this works for you. Otherwise, please let me know.

**Comment by jeanguyomarch** [comment] 2016-08-18 20:02
@jean-marc-LACROIX Any update?

**Comment by jean-marc-LACROIX** [comment] 2016-08-25 06:40
Hi jean,
I am working with your last patch in my git integration branch (commit b39d3f1457f49226af27902554b4588b87942f81)
In order to reproduce or not this issue, i use following command in my working dir:

export MANIFESTS_REVISION="dev/jeanmarc/kernel-4.7" && \
repo init -u https://github.com/sbxg/manifests -m "Cubietruck"/"linux.xml" -b $MANIFESTS_REVISION && \
make sync

Before running make menuconfig and after changing it, i confirm that CONFIG_HOSTNAME is correctly modified as follow:
local@solo:~/git/SBXG/sbxg.git$ diff .config .config.old
37c37

## < CONFIG_HOSTNAME="cubietruck"

> CONFIG_HOSTNAME="board-sbxg"

My proposal is to close this issue.
Thanks again

**Comment by jeanguyomarch** [comment] 2016-08-25 09:27
If that's settled, then, let's close the issue 👍

**Closed as completed by jeanguyomarch** 2016-08-25 09:27 UTC
